#Nether Banish Config

#OPTIONS
enabled: true

allowRoof: false
netherRoofHeight: 125

#Requires a Spawn point:
NetherWorld: world_nether
spawnX: -33
spawnY: 45
spawnZ: 73


#Messages
#Fires on user log in to server.
onBanish: 'You are you banished to the nether.  Enjoy your stay.'

#Respawns without anchors, 
onTeleport: 'There is no way out.'

#Fires for Portals, TP and pearls
onPortal: 'Normal methods will not free you.'

#Fires when in the nether above netherRoofHeight value
onRoof: 'You are not allowed above.'